name: Run Lint

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
